Use node-fetch; otherwise CLI won't compile for node.js
  ```
  40 | import { fetch } from "bun";
                           ^
  error: Browser build cannot import Bun builtin: "bun". When bundling for Bun, set target to 'bun'
      at ./offchain/cli/shared.ts:40:23
  error Command failed with exit code 1.
  ```

  Using `--target=bun` doesn't really fix the problem because it makes
  the build success, but the generated cli.js is unable to run as such
  and must be ran via `bun run dist/cli/cli.js` (since the generated
  shebang indicates node as an environment).

  Using `node-fetch` solves both the build, and the generated
  standalone executable.